[variables]
  NIXPACKS_PHP_VERSION = '8.4'

[phases.setup]
nixPkgs = [
  'php84',
  'php84Extensions.gd',
  'php84Extensions.intl',
  'php84Extensions.pdo',
  'php84Extensions.pdo_mysql',
  'php84Extensions.mbstring',
  'php84Extensions.zip',
  'php84Extensions.curl',
  'php84Extensions.fileinfo',
  'php84Extensions.tokenizer',
  'php84Extensions.xml',
  'php84Extensions.ctype',
  'php84Extensions.json',
  'php84Extensions.bcmath'
]

[phases.install]
cmds = [
  'composer install --optimize-autoloader --no-dev --no-interaction --ignore-platform-req=ext-intl --ignore-platform-req=ext-gd'
]

[phases.build]
cmds = [
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port='
