[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd"]

[phases.build]
cmds = ["composer install --optimize-autoloader --no-interaction"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
