[variables]
NIXPACKS_PHP_VERSION = '8.2'

[phases.setup]
nixPkgs = [
  'php82',
  'php82Extensions.gd',
  'php82Extensions.intl',
  'php82Extensions.pdo',
  'php82Extensions.pdo_mysql',
  'php82Extensions.mbstring',
  'php82Extensions.zip',
  'php82Extensions.curl',
  'php82Extensions.bcmath'
]

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev']

[phases.build]
cmds = [
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port='
